sisagro2/sisagro/apps/inicio/urls.py
from django.conf.urls import url
from .viewstotal import inicio
from .viewstotal import login
from .viewstotal import unidadmedida as uni
from .viewstotal import profesion as prof
from .viewstotal import especialidad as esp
from .viewstotal import tipoorganizacion as tiporg
from .viewstotal import mes
from .viewstotal import centropoblado as cenpo
from .viewstotal import caserio
from .viewstotal.profesionXLSX import *
from .viewstotal.tipoorganizacionXLSX import *

urlpatterns = [

	# LOGIN
    # url(r'^modelo/accion/$', ModeloAccion, name='modelo_accion'),
    url(r'^$', inicio.InicioView, name="inicio_view"),
    url(r'^login$', login.LoginView, name='user_login'),
    url(r'^logout$', login.LogoutView, name='user_logout'),

	# UNIDAD MEDIDA
    url(r'^unidadmedida/$', uni.UnidadMedidaView.as_view(), name='unidadmedida_inicio'),
    url(r'^unidadmedida/listar/$', uni.UnidadMedidaListView.as_view(), name='unidadmedida_listar'),
    url(r'^unidadmedida/crear/$', uni.UnidadMedidaCreateView.as_view(), name='unidadmedida_crear'),
    url(r'^unidadmedida/actualizar/(?P<pk>\d+)$', uni.UnidadMedidaUpdateView.as_view(), name='unidadmedida_actualizar'),
    url(r'^unidadmedida/eliminar/(?P<pk>\d+)$', uni.UnidadMedidaDeleteView.as_view(), name='unidadmedida_eliminar'),


    # PROFESION
    url(r'^profesion/listar/$', prof.ProfesionTemplateView.as_view(), name='profesion_inicio'),
    url(r'^profesion/listar/json$', prof.ListarProfesionJson.as_view(), name='profesion_listar'),
    url(r'^profesion/(?P<pk>\d+)/crear/$', prof.ProfesionCreateView.as_view(), name='profesion_create'),
    url(r'^profesion/(?P<pk>\d+)/eliminar/$', prof.ProfesionDeleteView.as_view(), name='profesion_delete'),
    url(r'^profesion/xlsx/$', ListaProfesionesXLS, name='profesion_xlsx'),

    # ESPECIALIDAD
    url(r'^especialidad/$', esp.EspecialidadView.as_view(), name='especialidad_inicio'),
    url(r'^especialidad/listar/$', esp.EspecialidadListView.as_view(), name='especialidad_listar'),
    url(r'^especialidad/crear/$', esp.EspecialidadCreateView.as_view(), name='especialidad_crear'),
    url(r'^especialidad/actualizar/(?P<pk>\d+)$', esp.EspecialidadUpdateView.as_view(), name='especialidad_actualizar'),
    url(r'^especialidad/eliminar/(?P<pk>\d+)$', esp.EspecialidadDeleteView.as_view(), name='especialidad_eliminar'),


    # MES
    url(r'^mes/$', mes.MesTemplateView.as_view(), name='mes_inicio'),
    url(r'^mes/listar/$', mes.ListarMesJson.as_view(), name='mes_listar'),
    url(r'^mes/(?P<pk>\d+)/crear/$', mes.MesCreateView.as_view(), name='profesion_create'),
    url(r'^mes/(?P<pk>\d+)/eliminar/$', mes.MesDeleteView.as_view(), name='profesion_eliminar'),

    # TIPO ORGANIZACION
    url(r'^tipoorganizacion/$', tiporg.TipoOrganizacionView.as_view(), name='tipoorganizacion_inicio'),
    url(r'^tipoorganizacion/listar/$', tiporg.TipoOrganizacionListView.as_view(), name='tipoorganizacion_listar'),
    url(r'^tipoorganizacion/crear/$', tiporg.TipoOrganizacionCreateView.as_view(), name='tipoorganizacion_crear'),
    url(r'^tipoorganizacion/actualizar/(?P<pk>\d+)$', tiporg.TipoOrganizacionUpdateView.as_view(), name='tipoorganizacion_actualizar'),
    url(r'^tipoorganizacion/eliminar/(?P<pk>\d+)$', tiporg.TipoOrganizacionDeleteView.as_view(), name='tipoorganizacion_eliminar'),
    url(r'^tipoorganizacion/xlsx/$', ListaTipoOrganizacionXLSX, name='tipoorganizacion_xlsx'),

    # CENTRO POBLADO
    url(r'^centropoblado/$', cenpo.CentroPobladoTemplateView.as_view(), name='centropoblado_inicio'),
    url(r'^centropoblado/listar/$', cenpo.CentroPobladoListView.as_view(), name='centropoblado_lista'),
    url(r'^centropoblado/crear/(?P<dist>\d+)$', cenpo.CentroPobladoCreateView.as_view(), name='centropoblado_crear'),
    url(r'^centropoblado/actualizar/(?P<pk>\d+)$', cenpo.CentroPobladoUpdateView.as_view(), name='centropoblado_actualizar'),
    url(r'^centropoblado/eliminar/(?P<pk>\d+)$', cenpo.CentroPobladoDeleteView.as_view(), name='centropoblado_eliminar'),
    url(r'^centropoblado/ubigeo/(?P<pk>\d+)/(?P<valor>\d+)/$', cenpo.ProvincaDistritoListView.as_view(), name='centropoblado_ubiego'),

    # CASERIO
    url(r'^caserio/$', caserio.CaserioTemplateView.as_view(), name='caserio_inicio'),
    url(r'^caserio/listar/$', caserio.CaserioListView.as_view(), name='caserio_lista'),
    url(r'^caserio/crear/(?P<cp>\d+)$', caserio.CaserioCreateView.as_view(), name='caserio_crear'),
    url(r'^caserio/actualizar/(?P<pk>\d+)$', caserio.CaserioUpdateView.as_view(), name='caserio_actualizar'),
    url(r'^caserio/eliminar/(?P<pk>\d+)$', caserio.CaserioDeleteView.as_view(), name='caserio_eliminar'),
    url(r'^caserio/ubigeo/(?P<pk>\d+)/(?P<valor>\d+)/$', caserio.ProvincaDistritoListView.as_view(), name='caserio_ubiego'),



]

sisagro2/sisagro/apps/planificacion/urls.py
from django.conf.urls import url

from .viewstotal import cadenaproductiva as cadpro
from .viewstotal import divisionfuncional as divfun
from .viewstotal import ejeecon as ejeco
from .viewstotal import funcion, pdrc, pdrcobjetivo
from .viewstotal import grupofuncional as grufun
from .viewstotal import indicador as indic
from .viewstotal import metaffprogramado as mffp
from .viewstotal import metaffejecutado as mffe
from .viewstotal import periodo as peri
from .viewstotal import subactividadcomponente as subactcpte
from .viewstotal import accionestrategica as accest
from .viewstotal import productoproyecto as propry
from .viewstotal import pdrcobjetivoespecifico as pdrcobjesp
from .viewstotal import aexpop
from .viewstotal import accionobra as accobr
from .viewstotal import actividad
from .viewstotal import programapresupuestal as propres
from .viewstotal import actividadcatalogo as actcat
from .viewstotal import subactividadcatalogo as subactcat
from .viewstotal import tareacatalogo as tarcat
from .viewstotal.accionestrategicaXLSX import *
from .viewstotal.programapresupuestalXLSX import *
from .viewstotal.productoproyectoXLSX import *
from .viewstotal.periodoXLSX import *
from .viewstotal.ejeeconXLSX import *
from .viewstotal.pdrcXLSX import *
from .viewstotal.pdrcobjetivoXLSX import *
from .viewstotal.pdrcobjetivoespecificoXLSX import *
from .viewstotal.aexpopXLSX import *
from .viewstotal.divisionfuncionalXLSX import *
from .viewstotal.funcionXLSX import *
from .viewstotal.grupofuncionalXLSX import *
from .viewstotal.cadenaproductivaXLSX import *

urlpatterns = [

    # ESPECIALIDAD
    url(r'^periodo/$', peri.PeriodoView.as_view(), name='periodo_inicio'),
    url(r'^periodo/listar/$', peri.PeriodoListView.as_view(), name='periodo_listar'),
    url(r'^periodo/crear/$', peri.PeriodoCreateView.as_view(), name='periodo_crear'),
    url(r'^periodo/actualizar/(?P<pk>\d+)$', peri.PeriodoUpdateView.as_view(), name='periodo_actualizar'),
    url(r'^periodo/eliminar/(?P<pk>\d+)$', peri.PeriodoDeleteView.as_view(), name='periodo_eliminar'),
    url(r'^periodo/xlsx/$', ListaPeriodosXLSX, name='periodo_xlsx'),

    # GRUPO FUNCIONAL
    url(r'^grupofuncional/$', grufun.GrupoFuncionalView.as_view(), name='grupofuncional_inicio'),
    url(r'^grupofuncional/listar/$', grufun.GrupoFuncionalListView.as_view(), name='grupofuncional_listar'),
    url(r'^grupofuncional/crear/$', grufun.GrupoFuncionalCreateView.as_view(), name='grupofuncional_crear'),
    url(r'^grupofuncional/actualizar/(?P<pk>\d+)$', grufun.GrupoFuncionalUpdateView.as_view(), name='grupofuncional_actualizar'),
    url(r'^grupofuncional/eliminar/(?P<pk>\d+)$', grufun.GrupoFuncionalDeleteView.as_view(), name='grupofuncional_eliminar'),
    url(r'^grupofuncional/xlsx/$', ListaGrupoFuncionalXLSX, name='grupofuncional_xlsx'),

    # INDICADOR
    url(r'^indicador/$', indic.IndicadorView.as_view(), name='indicador_inicio'),
    url(r'^indicador/listar/$', indic.IndicadorListView.as_view(), name='indicador_listar'),
    url(r'^indicador/crear/$', indic.IndicadorCreateView.as_view(), name='indicador_crear'),
    url(r'^indicador/actualizar/(?P<pk>\d+)$', indic.IndicadorUpdateView.as_view(), name='indicador_actualizar'),
    url(r'^indicador/eliminar/(?P<pk>\d+)$', indic.IndicadorDeleteView.as_view(), name='indicador_eliminar'),

    # EJE ECONOMICO
    url(r'^ejeecon/$', ejeco.EjeEconView.as_view(), name='ejeecon_inicio'),
    url(r'^ejeecon/listar/$', ejeco.EjeEconListView.as_view(), name='ejeecon_listar'),
    url(r'^ejeecon/crear/$', ejeco.EjeEconCreateView.as_view(), name='ejeecon_crear'),
    url(r'^ejeecon/actualizar/(?P<pk>\d+)$', ejeco.EjeEconUpdateView.as_view(), name='ejeecon_actualizar'),
    url(r'^ejeecon/eliminar/(?P<pk>\d+)$', ejeco.EjeEconDeleteView.as_view(), name='ejeecon_eliminar'),
    url(r'^ejeecon/xlsx/$', ListaEjesXLSX, name='ejeecon_xlsx'),

    # CADENA PRODUCTIVA
    url(r'^cadenaproductiva/$', cadpro.CadenaProductivaView.as_view(), name='cadenaproductiva_inicio'),
    url(r'^cadenaproductiva/listar/$', cadpro.CadenaProductivaListView.as_view(), name='cadenaproductiva_listar'),
    url(r'^cadenaproductiva/crear/$', cadpro.CadenaProductivaCreateView.as_view(), name='cadenaproductiva_crear'),
    url(r'^cadenaproductiva/actualizar/(?P<pk>\d+)$', cadpro.CadenaProductivaUpdateView.as_view(), name='cadenaproductiva_actualizar'),
    url(r'^cadenaproductiva/eliminar/(?P<pk>\d+)$', cadpro.CadenaProductivaDeleteView.as_view(), name='cadenaproductiva_eliminar'),
    url(r'^cadenaproductiva/xlsx/$', CadenaProductivaXLSX, name='cadenaproductiva_xlsx'),

    # FUNCION
  	url(r'^funcion/$', funcion.FuncionView.as_view(), name='funcion_inicio'),
    url(r'^funcion/listar/$', funcion.FuncionListView.as_view(), name='funcion_listar'),
    url(r'^funcion/crear/$', funcion.FuncionCreateView.as_view(), name='funcion_crear'),
    url(r'^funcion/actualizar/(?P<pk>\d+)$', funcion.FuncionUpdateView.as_view(), name='funcion_actualizar'),
    url(r'^funcion/eliminar/(?P<pk>\d+)$', funcion.FuncionDeleteView.as_view(), name='funcion_eliminar'),
    url(r'^funcion/xlsx/$', ListaFuncionXLSX, name='funcion_xlsx'),

    # PDRC
  	url(r'^pdrc/$', pdrc.PdrcView.as_view(), name='pdrc_inicio'),
	url(r'^pdrc/listar/$', pdrc.PdrcListView.as_view(), name='pdrc_listar'),
	url(r'^pdrc/crear/$', pdrc.PdrcCreateView.as_view(), name='pdrc_crear'),
	url(r'^pdrc/actualizar/(?P<pk>\d+)$', pdrc.PdrcUpdateView.as_view(), name='pdrc_actualizar'),
    url(r'^pdrc/eliminar/(?P<pk>\d+)$', pdrc.PdrcDeleteView.as_view(), name='pdrc_eliminar'),
	url(r'^pdrc/xlsx/$', ListaPDRCsXLSX, name='pdrc_xlsx'),

    # DIVISION FUNCIONAL
    url(r'^divisionfuncional/$', divfun.DivisionFuncionalView.as_view(), name='divisionfuncional_inicio'),
    url(r'^divisionfuncional/listar/$', divfun.DivisionFuncionalListView.as_view(), name='divisionfuncional_listar'),
    url(r'^divisionfuncional/crear/$', divfun.DivisionFuncionalCreateView.as_view(), name='divisionfuncional_crear'),
    url(r'^divisionfuncional/actualizar/(?P<pk>\d+)$', divfun.DivisionFuncionalUpdateView.as_view(), name='divisionfuncional_actualizar'),
    url(r'^divisionfuncional/eliminar/(?P<pk>\d+)$', divfun.DivisionFuncionalDeleteView.as_view(), name='divisionfuncional_eliminar'),
    url(r'^divisionfuncional/xlsx/$', ListaDivisionFuncionaXLSX, name='divisionfuncional_xlsx'),

    # META FISICA FINANCIERA - programada
    url(r'^metaffprogramado/$', mffp.MetaFFPTipoView.as_view(), name='metaffprogramado_inicio'),
    url(r'^metaffprogramado/prodproy/$', mffp.MetaFFPProdProyView.as_view(), name='metaffprogramado_prodproy'),
    url(r'^metaffprogramado/accest/$', mffp.MetaFFPAccEstView.as_view(), name='metaffprogramado_accionestrategica'),
    url(r'^metaffprogramado/actividad/$', mffp.MetaFFPActividadView.as_view(), name='metaffprogramado_actividad'),
    url(r'^metaffprogramado/tabla/(?P<pk>\d+)$', mffp.MetaFFPTableView.as_view(), name='metaffprogramado_tabla'),
    url(r'^metaffprogramado/actualizarmeta/$', mffp.MetaFFPUpdateView, name='metaffprogramado_actualizar'),

    # META FISICA FINANCIERA - ejecutada
    url(r'^metaffejecutado/$', mffe.MetaFFETipoView.as_view(), name='metaffejecutado_inicio'),
    url(r'^metaffejecutado/prodproy/$', mffe.MetaFFEProdProyView.as_view(), name='metaffejecutado_prodproy'),
    url(r'^metaffejecutado/accest/$', mffe.MetaFFEAccEstView.as_view(), name='metaffejecutado_accionestrategica'),
    url(r'^metaffejecutado/actividad/$', mffe.MetaFFEActividadView.as_view(), name='metaffejecutado_actividad'),
    url(r'^metaffejecutado/tabla/(?P<pk>\d+)$', mffe.MetaFFETableView.as_view(), name='metaffejecutado_tabla'),
    url(r'^metaffejecutado/actualizarmeta/$', mffe.MetaFFEUpdateView, name='metaffejecutado_actualizar'),

    # SUB ACTIVIDAD COMPONENTE
    url(r'^subactividadcomponente/$', subactcpte.SubActividadComponenteProdProyView.as_view(), name='subactividadcomponente_inicio'),
    url(r'^subactividadcomponente/accest/$', subactcpte.SubActividadComponenteAccEstView.as_view(), name='subactividadcomponente_accionestrategica'),
    url(r'^subactividadcomponente/actividad/$', subactcpte.SubActividadComponenteActividadView.as_view(), name='subactividadcomponente_actividad'),
    url(r'^subactividadcomponente/tabla/(?P<pk>\d+)$', subactcpte.SubActividadComponenteTablaView.as_view(), name='subactividadcomponente_tabla'),
    url(r'^subactividadcomponente/listar/(?P<act>\d+)$', subactcpte.SubActividadComponenteListView.as_view(), name='subactividadcomponente_listar'),
    url(r'^subactividadcomponente/crear/$', subactcpte.SubActividadComponenteCreateView.as_view(), name='subactividadcomponente_crear'),
    url(r'^subactividadcomponente/actualizar/(?P<pk>\d+)$', subactcpte.SubActividadComponenteUpdateView.as_view(), name='subactividadcomponente_actualizar'),
    url(r'^subactividadcomponente/eliminar/(?P<pk>\d+)$', subactcpte.SubActividadComponenteDeleteView.as_view(), name='subactividadcomponente_eliminar'),

    # OBJETIVOS PDRC
    url(r'^pdrcobjetivo/$', pdrcobjetivo.PdrcObjetivoView.as_view(), name='pdrcobjetivo_inicio'),
    url(r'^pdrcobjetivo/listar/$', pdrcobjetivo.PdrcObjetivoListView.as_view(), name='pdrcobjetivo_listar'),
    url(r'^pdrcobjetivo/crear/$', pdrcobjetivo.PdrcObjetivoCreateView.as_view(), name='pdrcobjetivo_crear'),
    url(r'^pdrcobjetivo/actualizar/(?P<pk>\d+)$', pdrcobjetivo.PdrcObjetivoUpdateView.as_view(), name='pdrcobjetivo_actualizar'),
    url(r'^pdrcobjetivo/eliminar/(?P<pk>\d+)$', pdrcobjetivo.PdrcObjetivoDeleteView.as_view(), name='pdrcobjetivo_eliminar'),
    url(r'^pdrcobjetivo/xlsx/$', ListaObjetivoPdrcXLSX, name='pdrcobjetivo_xlsx'),

    # OBJETIVOS ESPECIFICOS
    url(r'^pdrcobjesp/$', pdrcobjesp.ObjetivoEspecificoPdrcView.as_view(), name='objetivoespecifico_inicio'),
    url(r'^pdrcobjesp/pdrc/obj$', pdrcobjesp.ObjetivoEspecificoObjPdrcView.as_view(), name='objetivoespecifico_objpdrc'),

sisagro2/sisagro/sisagro/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # url(r'', login_required(TemplateView.as_view(template_name='inicio/login.html')), name='login_user'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include("apps.inicio.urls", namespace='home_base')),
    url(r'^inicio/', include("apps.inicio.urls", namespace='inicio')),
    url(r'^administracion/', include("apps.administracion.urls", namespace='administracion')),
    url(r'^planificacion/', include("apps.planificacion.urls", namespace='planificacion')),
    url(r'^agricola/', include("apps.agricola.urls", namespace='agricola')),
    url(r'^reportes/', include("apps.reportes.urls", namespace='reportes')),
    url(r'^select2/', include('django_select2.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sisagro2/sisagro/apps/inicio/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

sisagro2/sisagro/apps/planificacion/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

sisagro2/sisagro/apps/planificacion/templates/planificacion/divisionfuncional/eliminar.html
{% extends "base_form.html" %}
{% block form_body %}
    <form id="formDivisionFuncional" method='POST' class="form" role="form">
        {% csrf_token %}
        <input type="hidden" name="divisionfuncional_id" value="{{ divisionfuncional_id }}">
        {{ object.nombre }}
    </form>
    <script>
        var form_options = {
            target: $modalForm,
            success: function() {
            }
        }
        $formView = $('#formDivisionFuncional');
        $formView.ajaxForm(form_options);
    </script>
{% endblock form_body %}

sisagro2/sisagro/apps/planificacion/templates/planificacion/divisionfuncional/formulario.html
{% extends "base_form.html" %}
{% block form_body %}
    <form method='POST' id="formDivisionFuncional" >
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group row">
                <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label etiqueta">{{ field.label}}:</label>
                <div class="col-sm-10">
                    {{ field }}
                </div>
                {% for error in field.errors  %}
                <div class="col-sm-10 col-sm-offset-2" >
                    <label id="{{ field.id_for_label }}_label"for="{{ field.id_for_label }}" class="label-error">
                        {{ error|escape }}
                    </label>
                </div>
                {% endfor %}
            </div>
        {% endfor %}
    </form>
    <script>
        $formView = $('#formDivisionFuncional');
        var form_options = {
            target: $modalForm,
            success: function() {
            }
        }
        $formView.ajaxForm(form_options);
    </script>
{% endblock form_body %}

sisagro2/sisagro/apps/planificacion/templates/planificacion/divisionfuncional/inicio.html
{% extends "base_drac.html" %}
{% load static from staticfiles %}

{% block maestro_titulo %}

{% endblock maestro_titulo %}

{% block maestro_contenido %}
    <div id="toolbar">
        <button id="btnNuevo" type="button" class="btn btn-default" >
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        </button>
	</div>
	<table id="tablaDivisionFuncional"
		data-toolbar="#toolbar"
		data-toggle="table"
		data-url="{% url 'planificacion:divisionfuncional_listar' %}">
        <thead>
            <tr>
                <th data-field="nombre" data-sortable="true" data-switchable="true" class="col-md-11">Nombre</th>
                <th data-field="action" data-formatter="actionFormatter" data-switchable="false" data-events="actionEvents"
                    class="col-md-1" data-align="center">Acciones</th>
            </tr>
        </thead>
	</table>

    <div id="modalDivisionFuncional" class="modal fade" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"></h4>
          </div>
          <div class="modal-body">
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <button id="btnGuardar" type="button" class="btn btn-primary">Guardar</button>
          </div>
        </div>
      </div>
    </div>
{% endblock maestro_contenido %}

{% block maestro_scripts %}
    <script type="text/javascript">
        url_crear = "{% url 'planificacion:divisionfuncional_crear' %}";
        url_eliminar = "{% url 'planificacion:divisionfuncional_eliminar' 0 %}";
        url_eliminar = url_eliminar.substr(0, url_eliminar.length-1);
        url_editar = "{% url 'planificacion:divisionfuncional_actualizar' 0 %}";
        url_editar = url_editar.substr(0, url_editar.length-1);
        //
        $formTitulo = "División Funcional";
        $formGenero = "o";
        $modalForm = $("#modalDivisionFuncional");
        $tablaView = $("#tablaDivisionFuncional");
        $formView = null;
        $firstField = "id_nombre";
        opcion = "";
        idValue = 0;
        url_post = null;
    </script>
    <script src="{% static 'js/listagrilla.js' %}" type="text/javascript"></script>
{% endblock maestro_scripts %}