sisagro2/sisagro/apps/inicio/urls.py
from django.conf.urls import url
from .viewstotal import inicio
from .viewstotal import login
from .viewstotal import unidadmedida as uni
from .viewstotal import profesion as prof
from .viewstotal import especialidad as esp
from .viewstotal import tipoorganizacion as tiporg
from .viewstotal import mes
from .viewstotal import centropoblado as cenpo
from .viewstotal import caserio
from .viewstotal.profesionXLSX import *
from .viewstotal.tipoorganizacionXLSX import *

urlpatterns = [

	# LOGIN
    # url(r'^modelo/accion/$', ModeloAccion, name='modelo_accion'),
    url(r'^$', inicio.InicioView, name="inicio_view"),
    url(r'^login$', login.LoginView, name='user_login'),
    url(r'^logout$', login.LogoutView, name='user_logout'),

	# UNIDAD MEDIDA
    url(r'^unidadmedida/$', uni.UnidadMedidaView.as_view(), name='unidadmedida_inicio'),
    url(r'^unidadmedida/listar/$', uni.UnidadMedidaListView.as_view(), name='unidadmedida_listar'),
    url(r'^unidadmedida/crear/$', uni.UnidadMedidaCreateView.as_view(), name='unidadmedida_crear'),
    url(r'^unidadmedida/actualizar/(?P<pk>\d+)$', uni.UnidadMedidaUpdateView.as_view(), name='unidadmedida_actualizar'),
    url(r'^unidadmedida/eliminar/(?P<pk>\d+)$', uni.UnidadMedidaDeleteView.as_view(), name='unidadmedida_eliminar'),


    # PROFESION
    url(r'^profesion/listar/$', prof.ProfesionTemplateView.as_view(), name='profesion_inicio'),
    url(r'^profesion/listar/json$', prof.ListarProfesionJson.as_view(), name='profesion_listar'),
    url(r'^profesion/(?P<pk>\d+)/crear/$', prof.ProfesionCreateView.as_view(), name='profesion_create'),
    url(r'^profesion/(?P<pk>\d+)/eliminar/$', prof.ProfesionDeleteView.as_view(), name='profesion_delete'),
    url(r'^profesion/xlsx/$', ListaProfesionesXLS, name='profesion_xlsx'),

    # ESPECIALIDAD
    url(r'^especialidad/$', esp.EspecialidadView.as_view(), name='especialidad_inicio'),
    url(r'^especialidad/listar/$', esp.EspecialidadListView.as_view(), name='especialidad_listar'),
    url(r'^especialidad/crear/$', esp.EspecialidadCreateView.as_view(), name='especialidad_crear'),
    url(r'^especialidad/actualizar/(?P<pk>\d+)$', esp.EspecialidadUpdateView.as_view(), name='especialidad_actualizar'),
    url(r'^especialidad/eliminar/(?P<pk>\d+)$', esp.EspecialidadDeleteView.as_view(), name='especialidad_eliminar'),


    # MES
    url(r'^mes/$', mes.MesTemplateView.as_view(), name='mes_inicio'),
    url(r'^mes/listar/$', mes.ListarMesJson.as_view(), name='mes_listar'),
    url(r'^mes/(?P<pk>\d+)/crear/$', mes.MesCreateView.as_view(), name='profesion_create'),
    url(r'^mes/(?P<pk>\d+)/eliminar/$', mes.MesDeleteView.as_view(), name='profesion_eliminar'),

    # TIPO ORGANIZACION
    url(r'^tipoorganizacion/$', tiporg.TipoOrganizacionView.as_view(), name='tipoorganizacion_inicio'),
    url(r'^tipoorganizacion/listar/$', tiporg.TipoOrganizacionListView.as_view(), name='tipoorganizacion_listar'),
    url(r'^tipoorganizacion/crear/$', tiporg.TipoOrganizacionCreateView.as_view(), name='tipoorganizacion_crear'),
    url(r'^tipoorganizacion/actualizar/(?P<pk>\d+)$', tiporg.TipoOrganizacionUpdateView.as_view(), name='tipoorganizacion_actualizar'),
    url(r'^tipoorganizacion/eliminar/(?P<pk>\d+)$', tiporg.TipoOrganizacionDeleteView.as_view(), name='tipoorganizacion_eliminar'),
    url(r'^tipoorganizacion/xlsx/$', ListaTipoOrganizacionXLSX, name='tipoorganizacion_xlsx'),

    # CENTRO POBLADO
    url(r'^centropoblado/$', cenpo.CentroPobladoTemplateView.as_view(), name='centropoblado_inicio'),
    url(r'^centropoblado/listar/$', cenpo.CentroPobladoListView.as_view(), name='centropoblado_lista'),
    url(r'^centropoblado/crear/(?P<dist>\d+)$', cenpo.CentroPobladoCreateView.as_view(), name='centropoblado_crear'),
    url(r'^centropoblado/actualizar/(?P<pk>\d+)$', cenpo.CentroPobladoUpdateView.as_view(), name='centropoblado_actualizar'),
    url(r'^centropoblado/eliminar/(?P<pk>\d+)$', cenpo.CentroPobladoDeleteView.as_view(), name='centropoblado_eliminar'),
    url(r'^centropoblado/ubigeo/(?P<pk>\d+)/(?P<valor>\d+)/$', cenpo.ProvincaDistritoListView.as_view(), name='centropoblado_ubiego'),

    # CASERIO
    url(r'^caserio/$', caserio.CaserioTemplateView.as_view(), name='caserio_inicio'),
    url(r'^caserio/listar/$', caserio.CaserioListView.as_view(), name='caserio_lista'),
    url(r'^caserio/crear/(?P<cp>\d+)$', caserio.CaserioCreateView.as_view(), name='caserio_crear'),
    url(r'^caserio/actualizar/(?P<pk>\d+)$', caserio.CaserioUpdateView.as_view(), name='caserio_actualizar'),
    url(r'^caserio/eliminar/(?P<pk>\d+)$', caserio.CaserioDeleteView.as_view(), name='caserio_eliminar'),
    url(r'^caserio/ubigeo/(?P<pk>\d+)/(?P<valor>\d+)/$', caserio.ProvincaDistritoListView.as_view(), name='caserio_ubiego'),



]

sisagro2/sisagro/sisagro/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # url(r'', login_required(TemplateView.as_view(template_name='inicio/login.html')), name='login_user'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include("apps.inicio.urls", namespace='home_base')),
    url(r'^inicio/', include("apps.inicio.urls", namespace='inicio')),
    url(r'^administracion/', include("apps.administracion.urls", namespace='administracion')),
    url(r'^planificacion/', include("apps.planificacion.urls", namespace='planificacion')),
    url(r'^agricola/', include("apps.agricola.urls", namespace='agricola')),
    url(r'^reportes/', include("apps.reportes.urls", namespace='reportes')),
    url(r'^select2/', include('django_select2.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sisagro2/sisagro/apps/inicio/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
# Create your models here.
from django.http import HttpResponseRedirect

class Auditoria(models.Model):
	creado = models.DateTimeField(auto_now_add=True, editable=False)
	editado = models.DateTimeField(auto_now=True)
	creador = models.ForeignKey(User, related_name='+', on_delete=models.PROTECT)
	editor = models.ForeignKey(User, related_name='+', blank=True, null=True, on_delete=models.PROTECT)

	class Meta:
		abstract = True

class AuditableMixin(object,):

	def form_valid(self, form, ):
		if form.instance.id == None:
			form.instance.creador = self.request.user
		else:
			form.instance.editor = self.request.user
		return super(AuditableMixin, self).form_valid(form)

class UnidadMedida(Auditoria):
	nombre = models.CharField(max_length=100, unique=True)
	abreviatura = models.CharField(max_length=10, unique=True, default="", blank=True)

	class Meta:
		verbose_name = 'Unidad de Medida'
		verbose_name_plural = 'Unidades de Medida'

	def get_absolute_url(self):
		return ""

	def __unicode__(self):
		return self.nombre

class Mes(Auditoria):
	numero = models.SmallIntegerField(unique=True)
	nombre = models.CharField(max_length=15, unique=True)

	class Meta:
		verbose_name = 'Mes'
		verbose_name_plural = 'Meses'

	def __unicode__(self):
		return self.nombre

	def get_absolute_url(self):
		return ""

class Departamento(Auditoria):
	codigo = models.CharField(max_length=2, unique=True)
	nombre = models.CharField(max_length=45, unique=True)

	class Meta:
		verbose_name = 'Departamento'
		verbose_name_plural = 'Departamentos'

	def __unicode__(self):
		return self.nombre

	def get_absolute_url(self):
		return ""

class Provincia(Auditoria):
	codigo = models.CharField(max_length=4, unique=True)
	nombre = models.CharField(max_length=75)
	departamento = models.ForeignKey(Departamento, on_delete=models.PROTECT)

	class Meta:
		verbose_name = 'Provincia'
		verbose_name_plural = 'Provincias'

	def __unicode__(self):
		return self.nombre

	def get_absolute_url(self):
		return ""

class Distrito(Auditoria):
	codigo = models.CharField(max_length=6, unique=True)
	nombre = models.CharField(max_length=75)
	provincia = models.ForeignKey(Provincia, on_delete=models.PROTECT)

	class Meta:
		verbose_name = 'Distrito'
		verbose_name_plural = 'Distritos'

	def __unicode__(self):
		return self.nombre

	def get_absolute_url(self):
		return ""

class CentroPoblado(Auditoria):
	codigo = models.CharField(max_length=10, unique=True)
	nombre = models.CharField(max_length=45)
	area = models.CharField(max_length=15)
	distrito = models.ForeignKey(Distrito, on_delete=models.PROTECT)

	class Meta:
		verbose_name = 'Centro Poblado'
		verbose_name_plural = 'Centros Poblados'

	def __unicode__(self):
		return self.nombre

	def get_absolute_url(self):
		return ""

class Caserio(Auditoria):
	codigo = models.CharField(max_length=12, unique=True)
	nombre = models.CharField(max_length=45)
	centropoblado = models.ForeignKey(CentroPoblado, on_delete=models.PROTECT)

	class Meta:
		verbose_name = 'Caserío'
		verbose_name_plural = 'Caseríos'

	def __unicode__(self):
		return self.nombre

	def get_absolute_url(self):
		return ""

class Profesion(Auditoria):
	nombre = models.CharField(max_length=100, unique=True)

	class Meta:
		verbose_name = 'Profesión'
		verbose_name_plural = 'Profesiones'

	def get_absolute_url(self):
		return ""

	def __unicode__(self):
		return self.nombre

class Especialidad(Auditoria):
	nombre = models.CharField(max_length=100, unique=True)

	class Meta:
		verbose_name = 'Especialidad'
		verbose_name_plural = 'Especialidades'

	def __unicode__(self):
		return self.nombre

	def get_absolute_url(self):
		return ""

class TipoOrganizacion(Auditoria):
	nombre = models.CharField(max_length=75, unique=True)
	estado = models.BooleanField(default=True)

	class Meta:
		verbose_name = 'Tipo de Organización'
		verbose_name_plural = 'Tipos de Organizaciones'

	def __unicode__(self):
		return self.nombre

	def get_absolute_url(self):
		return ""

sisagro2/sisagro/apps/inicio/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

sisagro2/sisagro/apps/inicio/templates/inicio/unidadmedida/eliminar.html
{% extends "base_form.html" %}
{% block form_body %}
    <form id="formUnidadMedida" method='POST' class="form" role="form">
        {% csrf_token %}
        <input type="hidden" name="unidadmedida_id" value="{{ unidadmedida_id }}">
        {{ object.nombre }} - {{ object.abreviatura }}
    </form>
    <script>
        var form_options = {
            target: $modalForm,
            success: function() {
            }
        }
        $formView = $('#formUnidadMedida');
        $formView.ajaxForm(form_options);
    </script>
{% endblock form_body %}

sisagro2/sisagro/apps/inicio/templates/inicio/unidadmedida/formulario.html
{% extends "base_form.html" %}
{% block form_body %}
    <form method='POST' id="formUnidadMedida" >
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group row">
                <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label}}:</label>
                <div class="col-sm-10">
                    {{ field }}
                </div>
                {% for error in field.errors  %}
                <div class="col-sm-10 col-sm-offset-2" >
                    <label id="{{ field.id_for_label }}_label"for="{{ field.id_for_label }}" class="label-error">
                        {{ error|escape }}
                    </label>
                </div>
                {% endfor %}
            </div>
        {% endfor %}
    </form>
    <script>
        $formView = $('#formUnidadMedida');
        var form_options = {
            target: $modalForm,
            success: function() {
            }
        }
        $formView.ajaxForm(form_options);
    </script>
{% endblock form_body %}

sisagro2/sisagro/apps/inicio/templates/inicio/unidadmedida/inicio.html
{% extends "base_drac.html" %}
{% load static from staticfiles %}

{% block maestro_titulo %}
{% endblock maestro_titulo %}

{% block maestro_contenido %}
    <div id="toolbar">
        <button id="btnNuevo" type="button" class="btn btn-default" >
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        </button>
	</div>
	<table id="tablaUnidadMedida"
		data-toolbar="#toolbar"
		data-toggle="table"
		data-url="{% url 'inicio:unidadmedida_listar' %}">
	    <thead>
	        <tr>
	        	<th data-field="id" data-visible="false" class="col-md-1" data-switchable="false">id</th>
            	<th data-field="nombre" data-sortable="true" data-switchable="true" class="col-md-6">Nombre</th>
            	<th data-field="abreviatura" data-sortable="true" data-switchable="true" class="col-md-4">Abreviatura</th>
            	<th data-field="action" data-formatter="actionFormatter" data-switchable="false"
                    data-events="actionEvents" class="col-md-1" data-align="center">Acciones</th>
	        </tr>
	    </thead>
	</table>
    <div id="modalUnidadMedida" class="modal fade" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"></h4>
          </div>
          <div class="modal-body">
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <button id="btnGuardar" type="button" class="btn btn-primary">Guardar Cambios</button>
          </div>
        </div>
      </div>
    </div>
{% endblock maestro_contenido %}

{% block maestro_scripts %}
    <script type="text/javascript">
        url_crear = "{% url 'inicio:unidadmedida_crear' %}";
        url_eliminar = "{% url 'inicio:unidadmedida_eliminar' 0 %}";
        url_eliminar = url_eliminar.substr(0, url_eliminar.length-1);
        url_editar = "{% url 'inicio:unidadmedida_actualizar' 0 %}";
        url_editar = url_editar.substr(0, url_editar.length-1);
        //
        $formTitulo = "Unidad de Medida";
        $formGenero = "a";
        $modalForm = $("#modalUnidadMedida");
        $tablaView = $("#tablaUnidadMedida");
        $formView = null;
        $firstField = "id_nombre";
        opcion = "";
        idValue = 0;
        url_post = null;
    </script>
    <script src="{% static 'js/listagrilla.js' %}" type="text/javascript"></script>
{% endblock maestro_scripts %}